// Renders data/generated-results.json as README.md, the repo's front page.
import { readFileSync, writeFileSync } from 'node:fs';

const { checkedAt, opcodes, tvl, snippetCheck, chains } = JSON.parse(readFileSync('data/generated-results.json', 'utf8'));

const CELL = { supported: 'yes', unsupported: 'no', unknown: '?' };
const cell = (v) =>
	v.documented ? `${CELL[v.documented.status]}*` : v.observed ? `${CELL[v.observed]}~` : CELL[v.status];
const usd = (n) => (n >= 1e9 ? `$${(n / 1e9).toFixed(1)}B` : `$${Math.round(n / 1e6)}M`);
const pct = (part, whole) => `${((part / whole) * 100).toFixed(1)}%`;
const readable = (iso) => {
	const d = new Date(iso);
	const day = d.getUTCDate();
	const month = d.toLocaleString('en-GB', { month: 'long', timeZone: 'UTC' });
	const time = `${String(d.getUTCHours()).padStart(2, '0')}:${String(d.getUTCMinutes()).padStart(2, '0')}`;
	return `${day} ${month} ${d.getUTCFullYear()}, ${time} UTC`;
};

const table = (headers, rows) =>
	[`| ${headers.join(' | ')} |`, `| ${headers.map(() => '---').join(' | ')} |`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');

// One answer per cell, whatever its source: two operators agreeing, one operator observing, or a
// primary source. The matrix shows which, so the summary does not need to.
const supported = (opcode) =>
	chains.filter((chain) => {
		const v = chain.opcodes[opcode.name];
		const seen = v.confidence === 'confirmed' ? v.status : (v.observed ?? v.documented?.status);
		return seen === 'supported';
	}).length;

const summary = table(
	['opcode', 'byte', 'fork', 'EIP', 'supported'],
	opcodes.map((opcode) => {
		const yes = supported(opcode);
		return [
			`\`${opcode.name}\``,
			`\`${opcode.byte}\``,
			opcode.fork,
			opcode.eip,
			`**${Math.round((yes / chains.length) * 100)}%** (${yes} of ${chains.length})`,
		];
	}),
);

const matrix = table(
	['#', 'chain', 'chain id', 'TVL', ...opcodes.map((o) => o.name)],
	chains.map((chain, i) => [
		i + 1,
		chain.name,
		chain.chainId,
		usd(chain.tvlUsd),
		...opcodes.map((o) => cell(chain.opcodes[o.name])),
	]),
);

const representativeness = tvl?.totalEvmUsd
	? `The top ${tvl.topN} EVM chains by TVL, ranked by DefiLlama with endpoints from \`ethereum-lists/chains\`. The last run produced a verdict covering **${pct(
			tvl.analyzedUsd,
			tvl.totalEvmUsd,
		)} of EVM TVL** (${usd(tvl.analyzedUsd)}).`
	: `The top ${chains.length} EVM chains by TVL, ranked by DefiLlama.`;

const documented = chains.filter((c) => opcodes.some((o) => c.opcodes[o.name].documented));
const singleOperator = chains.filter((c) => opcodes.some((o) => c.opcodes[o.name].observed));

const documentedNote = documented.length
	? `\`*\` from a primary source because no probe reaches that chain: ${documented
			.map((c) => `${c.name} ([source](${opcodes.map((o) => c.opcodes[o.name].documented).find(Boolean).source}))`)
			.join(', ')}`
	: '';

const notes = [
	'`yes` supported',
	'`no` unsupported',
	'`?` no verdict',
	singleOperator.length
		? `\`~\` observed, but by a single operator, so not confirmed: ${singleOperator.map((c) => c.name).join(', ')}`
		: '',
	documentedNote,
].filter(Boolean);

const warning = snippetCheck.suspectSnippets.length
	? `\n**Warning:** unsupported on the reference chain, snippet likely malformed: ${snippetCheck.suspectSnippets.join(', ')}.\n`
	: '';

writeFileSync(
	'README.md',
	`# EVM Opcode Support

Which EVM opcodes are supported on which chains, measured periodically against live nodes.

- **Last updated:** ${readable(checkedAt)}
- **Refreshed:** daily at 06:00 UTC
- **How this is measured:** [METHOD.md](./METHOD.md)

## Representativeness

${representativeness}
${warning}
## Summary

${summary}

## Top 50 EVM Chains Opcodes Support

${matrix}

${notes.map((n) => `- ${n}`).join('\n')}

## Method

Calibrated probes, two independent operators per verdict, no gas: see [METHOD.md](./METHOD.md).
\`data/generated-results.json\` carries the per-endpoint evidence behind every cell.

This page is generated by \`npm run report\`. Do not edit it by hand.
`,
);
console.log(`wrote README.md (${chains.length} chains, ${opcodes.length} opcodes)`);
