// Renders data/results.json as REPORT.md.
import { readFileSync, writeFileSync } from 'node:fs';
import { operator } from './endpoints.mjs';

const { checkedAt, opcodes, coverage, snippetCheck, chains } = JSON.parse(readFileSync('data/results.json', 'utf8'));

const CELL = { supported: 'yes', unsupported: 'no', unknown: '?' };
const usd = (n) => (n >= 1e9 ? `$${(n / 1e9).toFixed(1)}B` : `$${Math.round(n / 1e6)}M`);
const names = (chains) => (chains.length ? chains.map((c) => c.name).join(', ') : 'none');
const operators = (chain) => new Set(chain.witnesses.filter((w) => w.calibrated).map((w) => operator(w.url))).size;

const table = (headers, rows) =>
	[`| ${headers.join(' | ')} |`, `| ${headers.map(() => '---').join(' | ')} |`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');

const groupsByOpcode = new Map(
	opcodes.map((opcode) => {
		const group = { supported: [], unsupported: [], unknown: [] };
		for (const chain of chains) group[chain.opcodes[opcode.name].status].push(chain);
		return [opcode.name, group];
	}),
);

const summary = table(
	['opcode', 'byte', 'fork', 'EIP', 'supported', 'unsupported', 'unconfirmed', 'support'],
	opcodes.map((opcode) => {
		const { supported, unsupported, unknown } = groupsByOpcode.get(opcode.name);
		const confirmed = supported.length + unsupported.length;
		const pct = confirmed ? `${Math.round((supported.length / confirmed) * 100)}%` : 'n/a';
		return [
			`\`${opcode.name}\``,
			`\`${opcode.byte}\``,
			opcode.fork,
			opcode.eip,
			supported.length,
			unsupported.length,
			unknown.length,
			`**${pct}** of ${confirmed} confirmed`,
		];
	}),
);

const perOpcode = opcodes
	.map((opcode) => {
		const { supported, unsupported, unknown } = groupsByOpcode.get(opcode.name);
		return [
			`## ${opcode.name} (\`${opcode.byte}\`, ${opcode.fork}, ${opcode.eip})`,
			'',
			`- **Supported (${supported.length}):** ${names(supported)}`,
			`- **Not supported (${unsupported.length}):** ${names(unsupported)}`,
			`- **Unconfirmed (${unknown.length}):** ${names(unknown)}`,
		].join('\n');
	})
	.join('\n\n');

const matrix = table(
	['#', 'chain', 'chain id', 'TVL', ...opcodes.map((o) => o.name), 'operators'],
	chains.map((chain, i) => [
		i + 1,
		chain.name,
		chain.chainId,
		usd(chain.tvlUsd),
		...opcodes.map((o) => CELL[chain.opcodes[o.name].status]),
		operators(chain),
	]),
);

const unresolved = chains.filter((c) => opcodes.some((o) => c.opcodes[o.name].status === 'unknown'));
const unconfirmed = unresolved.length
	? [
			'## Unconfirmed chains',
			'',
			table(
				['chain', 'reason', 'detail'],
				unresolved.map((chain) => {
					const verdict = opcodes.map((o) => chain.opcodes[o.name]).find((v) => v.status === 'unknown');
					const rejections = [
						...new Set(chain.witnesses.filter((w) => !w.calibrated).flatMap((w) => Object.values(w.rejected ?? {}))),
					].slice(0, 2);
					return [chain.name, verdict.confidence, rejections.join('; ') || 'see data/results.json'];
				}),
			),
			'',
		].join('\n')
	: '';

writeFileSync(
	'REPORT.md',
	`# EVM opcode support, top 30 chains by TVL

Checked ${checkedAt}. Generated by \`scripts/probe.mjs\`, do not edit by hand.

Every check is a read-only \`eth_call\` simulation, so no transaction is ever sent and no gas is spent.
A verdict is only recorded when two calibrated endpoints run by **different operators** agree.
Percentages count confirmed verdicts only.

Coverage: ${coverage.byConfidence.confirmed ?? 0} of ${coverage.cells} cells confirmed${
		Object.entries(coverage.byConfidence)
			.filter(([k]) => k !== 'confirmed')
			.map(([k, n]) => `, ${n} ${k}`)
			.join('') || ''
	}.${snippetCheck.suspectSnippets.length ? `\n\n**Warning:** unsupported on the reference chain, snippet likely malformed: ${snippetCheck.suspectSnippets.join(', ')}.` : ''}

## Summary

${summary}

${perOpcode}

## Matrix

${matrix}

${unconfirmed}
## Method

Each opcode is probed with a snippet whose stack inputs are satisfied by \`PUSH0\`, executed two
read-only ways: \`eth_call\` with a state override, then \`eth_call\` with no \`to\`. An endpoint counts
only after \`STOP\` succeeds and \`0x0c\`, undefined in every fork, fails. Failures not attributable to
the EVM, such as rate limits, are recorded as unconfirmed rather than unsupported.

See [README](./README.md) for the full method and its limits.
`,
);
console.log(`wrote REPORT.md (${chains.length} chains, ${opcodes.length} opcodes)`);
