// Renders data/generated-results.json as README.md, the repo's front page.
import { readFileSync, writeFileSync } from 'node:fs';

const { checkedAt, opcodes, tvl, snippetCheck, chains } = JSON.parse(readFileSync('data/generated-results.json', 'utf8'));

const CELL = { supported: 'yes', unsupported: 'no', unknown: '?' };
const cell = (v) => (v.documented ? `${CELL[v.documented.status]}*` : CELL[v.status]);
const usd = (n) => (n >= 1e9 ? `$${(n / 1e9).toFixed(1)}B` : `$${Math.round(n / 1e6)}M`);
const pct = (part, whole) => `${((part / whole) * 100).toFixed(1)}%`;

const table = (headers, rows) =>
	[`| ${headers.join(' | ')} |`, `| ${headers.map(() => '---').join(' | ')} |`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');

const statusCounts = (opcode) => {
	const counts = { supported: 0, unsupported: 0, unknown: 0 };
	for (const chain of chains) counts[chain.opcodes[opcode.name].status]++;
	return counts;
};

const summary = table(
	['opcode', 'byte', 'fork', 'EIP', 'supported', 'unsupported', 'unconfirmed', 'support'],
	opcodes.map((opcode) => {
		const { supported, unsupported, unknown } = statusCounts(opcode);
		const confirmed = supported + unsupported;
		return [
			`\`${opcode.name}\``,
			`\`${opcode.byte}\``,
			opcode.fork,
			opcode.eip,
			supported,
			unsupported,
			unknown,
			confirmed ? `**${Math.round((supported / confirmed) * 100)}%** of ${confirmed} confirmed` : 'n/a',
		];
	}),
);

const matrix = table(
	['#', 'chain', 'chain id', 'TVL', ...opcodes.map((o) => o.name)],
	chains.map((chain, i) => [
		i + 1,
		chain.name,
		chain.chainId,
		usd(chain.tvlUsd),
		...opcodes.map((o) => cell(chain.opcodes[o.name])),
	]),
);

const representativeness = tvl?.totalEvmUsd
	? `The top ${tvl.topN} EVM chains by TVL, as ranked by DefiLlama. Chains that produced a verdict hold ${usd(
			tvl.analyzedUsd,
		)}, **${pct(tvl.analyzedUsd, tvl.totalEvmUsd)} of EVM TVL**. Chains we could not scan do not count${
			tvl.unscanned.length ? `: ${tvl.unscanned.map((c) => c.name).join(', ')}` : ''
		}.`
	: `The top ${chains.length} EVM chains by TVL, as ranked by DefiLlama.`;

const generic = chains.flatMap((c) =>
	opcodes.filter((o) => c.opcodes[o.name].grade === 'generic').map((o) => `${c.name}/${o.name}`),
);
const documented = chains.filter((c) => opcodes.some((o) => c.opcodes[o.name].documented));

const notes = [
	documented.length
		? `\`*\` not probeable, taken from a primary source and excluded from the percentages: ${documented
				.map((c) => `${c.name} ([source](${opcodes.map((o) => c.opcodes[o.name].documented).find(Boolean).source}))`)
				.join(', ')}.`
		: '',
	generic.length
		? `Weakest evidence, an unsupported verdict backed by a generic error rather than a named opcode: ${generic.join(', ')}.`
		: '',
].filter(Boolean);

const warning = snippetCheck.suspectSnippets.length
	? `\n**Warning:** unsupported on the reference chain, snippet likely malformed: ${snippetCheck.suspectSnippets.join(', ')}.\n`
	: '';

writeFileSync(
	'README.md',
	`# EVM Opcode Support Report

Which EVM opcodes are supported on which chains, measured against live nodes instead of read off
documentation.

- **Last updated:** ${checkedAt}
- **Refreshed:** daily at 06:00 UTC, and on demand after a hardfork
- **How this is measured:** [METHOD.md](./METHOD.md)

Cells: \`yes\` supported, \`no\` unsupported, \`?\` no verdict, \`*\` from a primary source because no
probe reaches that chain. Generated by \`npm run report\`, do not edit by hand.

## Representativeness

${representativeness}
${warning}
## Summary

${summary}

## Matrix

${matrix}

${notes.map((n) => `- ${n}`).join('\n')}

## Method

Calibrated probes, two independent operators per verdict, no gas: see [METHOD.md](./METHOD.md).
\`data/generated-results.json\` carries the per-endpoint evidence behind every cell.
`,
);
console.log(`wrote README.md (${chains.length} chains, ${opcodes.length} opcodes)`);
